#ifndef __GAMEREND_H
#define __GAMEREND_H

#define REDACTEDGAME 1

#if REDACTEDGAME

#define ASSUME_PERSPECTIVE_CAMERA 1

#define ENABLE_ZSORT 0
#define ENABLE_FACE_GROUP_COUNT 1
#define TEXTURE_GROUPS_HACK 1

#define TRANSFORMPROJECT_SEPARATE_LOOP 1

#else

#define ASSUME_PERSPECTIVE_CAMERA 0

#define ENABLE_ZSORT 1
#define ENABLE_FACE_GROUP_COUNT 0
#define TEXTURE_GROUPS_HACK 0

#define TRANSFORMPROJECT_SEPARATE_LOOP 0

#endif

#endif //__GAMEREND_H
